--Find total customers by country
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC
--Find total customers by gender

SELECT
gender,
COUNT(customer_key) AS customers_by_gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY customers_by_gender DESC

--Find total products by category
SELECT
category,
COUNT(product_key) AS products_category
FROM gold.dim_products
GROUP BY category
ORDER BY products_category DESC

--What is the average costs in each category?
SELECT
category,
AVG(cost) AS category_average
FROM gold.dim_products
GROUP BY category
ORDER BY category_average DESC


--What is te total revenue generated for each category?
SELECT
p.category,
SUM(s.sales_amount) AS category_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p ON s.product_key = p.product_key 
GROUP BY p.category
ORDER BY category_revenue DESC


--Find total revenue is generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c ON c.customer_key = s.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

--What is the distribution of sold items across countries
SELECT
c.country,
COUNT(s.product_key) AS total_sold_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC